name: CD to Azure Web App

on: 
  push:
    branches:
      - 'main'
  
jobs:
  build-ws:
    name: "Build Web Server"
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: npm install, build, and test ui
        working-directory: './chat-ui'
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: npm install, build, and test ws
        working-directory: './chat-ws'
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  containerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/chat-ws:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/chat-ws:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-ws
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatwsappserviceg6'
          slot-name: 'Production'
          package: './chat-ws'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_10E2DB9116264408928A3EA015FD33BB }}
          
